### ISSUE TITLE
Team24ev iFrame weirdly recursive on some browsers

### ISSUE THREAD

**Issue by lorsposto** [USCDataScience/polar.usc.edu#116]
On initial load iframe html/team24ev/team24-histogram.html is filled by the page itself. Found in Chrome and Safari, but not Firefox

**Comment by skashyap7** [comment]
@lorsposto : Hey, Do you want me to fix my pages and make them consistent like other visualizations !

**Comment by lorsposto** [comment]
hey @skashyap7, it actually looks okay overall. The only issue is that for metadata quality score (histogram) the iframe displays the page itself until a link is clicked to show a specific visualization. If you feel up to it, go ahead and fix it, otherwise one of the team will take it! (realized I forgot to assign this issue)

**Comment by chrismattmann** [comment]
going to close this for now
