### ISSUE TITLE
Search URL in menu bar not working

### ISSUE THREAD

**Issue by trevorlewis** [USCDataScience/polar.usc.edu#12]
The URL in the top menu bar points to:
http://localhost:8983/solr/banana/src/index.html#/dashboard
So I am getting a "This webpage is not available" message.

**Comment by titusjung** [comment]
I added a drop down option to the search button that has links to the Banana dashboard and facetview pages. This fix is on the gh-pages branch and needs to be updated to the server.
<img width="568" alt="polar dropdown fix" src="https://cloud.githubusercontent.com/assets/10523055/13471175/4d61c3ca-e064-11e5-8fba-0445ce015e2a.PNG">

**Comment by lorsposto** [comment]
Looks good from the screen shot. It doesn't need to be updated on the server, polar.usc.edu pulls directly from gh-pages.
