### ISSUE TITLE
Team using verbatim copy of cloud.min.js for word cloud - Team6 EV

### ISSUE THREAD

**Issue by chrismattmann** [USCDataScience/polar.usc.edu#123]
I received a message from Jason Davie mentioning that there is a near-verbatim copy of his word cloud generator on the "Polar Data Insights" site (except with some of the original page controls hidden on load): http://polar.usc.edu/html/team6ev/sweet_dict_intersection.html. He would prefer that we don't copy his code verbatim. Thus, please take down the Word Cloud for Team6 EV.

Jason asks if we can remove the infringing code (cloud.min.js) and to remove the copy of his Google AdSense banner!  (The <ins> and pagead2.googlesyndication.com reference).

**Comment by chrismattmann** [comment]
@lorsposto please handle this ASAP

**Comment by lorsposto** [comment]
@chrismattmann got it

**Comment by chrismattmann** [comment]
@lorsposto the page still remains for some reason, try:

http://polar.usc.edu/html/team6ev/sweet_dict_intersection.html

**Comment by chrismattmann** [comment]
strangely enough this doesn't work:
http://irds.usc.edu/polar.usc.edu/html/team6ev/sweet_dict_intersection.html and properly gives a 404

**Comment by chrismattmann** [comment]
I found this: http://stackoverflow.com/questions/16065693/github-pages-still-serving-deleted-files

**Comment by chrismattmann** [comment]
@pzimdars please help.

**Comment by chrismattmann** [comment]
OK I can confirm this is fixed, thanks @lorsposto 

```
[polardeploy@drat team6ev]$ curl "http://polar.usc.edu/html/team6ev/sweet_dict_intersection.html"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /html/team6ev/sweet_dict_intersection.html was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at polar.usc.edu Port 80</address>
</body></html>
[polardeploy@drat team6ev]$ 
```
