### ISSUE TITLE
Research panels to add temporal/geo topics to Banana

### ISSUE THREAD

**Issue by lorsposto** [USCDataScience/polar.usc.edu#127]
Vague issue, but more of a reminder to look at other panel types in Banana (quick glance, there is "betterMap" and "heatmap") to add.

@luuj

**Comment by lorsposto** [comment]
@janethkim

**Comment by chrismattmann** [comment]
ping @lorsposto is this one going to happen?

**Comment by chrismattmann** [comment]
I think it's fine I like Banana now we can research this later. All issues fixed now, so can you all plow through PRs?
