### ISSUE TITLE
How to contribute to visualisations?

### ISSUE THREAD

**Issue by rahulravindran0108** [USCDataScience/polar.usc.edu#13]
I have some interesting visualisations on the polar dataset available at:
http://rahulravindran0108.github.io/Polar-Dataset-Explorer/

Should I send a pull request over with changes in the gh-pages branch ?

**Comment by lorsposto** [comment]
yes please! the gh-pages branch is perfect

**Comment by ruthvik947** [comment]
Hi Rahul. I believe that would be ideal, yes. Do you have your data stored locally/is it static content?

**Comment by rahulravindran0108** [comment]
Yes. It is static content. Data is present in json files. So what I will do is create a new tab and build a page that looks like a gallery. Would that be fine ?

So others can simply point to their visualisations/ gh-pages

**Comment by ruthvik947** [comment]
That sounds perfect! (also FYI, the readme in the gh-pages is a little outdated at the moment)

**Comment by rahulravindran0108** [comment]
@lorsposto Sent a pull over. See #14 for details.
