### ISSUE TITLE
team11 visualization issues

### ISSUE THREAD

**Issue by chrismattmann** [USCDataScience/polar.usc.edu#130]
See: http://polar.usc.edu/html/team11/index.html

Please:
1. fix the screenshot preview on the gallery page (replace with working image thumbnail)
2. disable the first 2 visualizations that don't work (remove links to them)

**Comment by chrismattmann** [comment]
@lorsposto can you all please finish this off?

**Comment by titusjung** [comment]
should be fixed now

**Comment by chrismattmann** [comment]
Fixed thanks @titusjung
