### ISSUE TITLE
Data science link updates

### ISSUE THREAD

**Issue by lorsposto** [USCDataScience/polar.usc.edu#19]
See these notes:
![screen shot 2016-03-07 at 10 55 36 am](https://cloud.githubusercontent.com/assets/6422954/13579664/87eb9a00-e453-11e5-9dee-067592da1260.png)

**Comment by luuj** [comment]
TODO: Add Credits header, add descriptions to the three panels.

**Comment by luuj** [comment]
Added descriptions for the three panels. @chrismattmann Could you let me know if you want any changes to these descriptions, thanks!

**Comment by luuj** [comment]
Added a credits section
