### ISSUE TITLE
Create new "Data" tab for MIME type viz

### ISSUE THREAD

**Issue by lorsposto** [USCDataScience/polar.usc.edu#25]
- Separate 599's MIME type viz from the other D3 stuff, as a separate tab in the nav
- Have it there along with the TREC description

"Site should be about the data and its description aka the TREC desription I wrote in Github"

**Comment by lorsposto** [comment]
This is especially relevant now that there is more than one MIME type group contribution. Note the two gallery items:

![screen shot 2016-03-08 at 9 46 00 pm](https://cloud.githubusercontent.com/assets/6422954/13626476/311a4184-e577-11e5-9652-df5e77788e65.png)

@luuj @ruthvik947 @titusjung @janethkim would someone especially like to claim this?

**Comment by ruthvik947** [comment]
I can take this!

**Comment by chrismattmann** [comment]
closed in #38
