### ISSUE TITLE
FacetView and Banana page consistent with USC Branding

### ISSUE THREAD

**Issue by janethkim** [USCDataScience/polar.usc.edu#26]

**Comment by chrismattmann** [comment]
@janethkim @lorsposto this is becoming a priority. Where are we with this?

**Comment by janethkim** [comment]
I've done the FacetView portion on a different branch, but will do the Banana page tonight

**Comment by chrismattmann** [comment]
ok can you please create a PR for the FacetView portion ASAP so I can review and we can merge @janethkim ? For the Banana page, tonight would be great too I'm happy to review once done.

**Comment by lorsposto** [comment]
@janethkim what's the status on this?

**Comment by janethkim** [comment]
just merged work on Facetview branding with master
will get started on brushing that up and banana today

**Comment by lorsposto** [comment]
@janethkim Facetview looks good. Might make a new ticket for some updates to the content of the nav bar in relation the main page, after we discuss what links should be put there -- maybe the nav content should be consistent across all pages. Good start though!

**Comment by janethkim** [comment]
okay I'm working on the banana page now just to get usc branding consistent - so you mean the nav content should be the same as the main polar.usc,edu page?

**Comment by lorsposto** [comment]
Continue with how you were doing it, with the links how they are, but yes the content of the nav bars should be something we discuss for the future

**Comment by chrismattmann** [comment]
nav bar content should be consistent across all pages.  @janethkim @lorsposto

**Comment by lorsposto** [comment]
for nav consistency see #46
