### ISSUE TITLE
Fix splash page buttons (low priority)

### ISSUE THREAD

**Issue by luuj** [USCDataScience/polar.usc.edu#43]
![screen shot 2016-03-20 at 5 39 45 pm](https://cloud.githubusercontent.com/assets/6404272/13908583/cb7ffe04-eec2-11e5-8b4d-f375c046aa91.png)

When you adjust the size of the window so that the height is below a certain number, the 'Learn more' and 'View Visualizations' buttons disappear.

**Comment by lorsposto** [comment]
Additionally, the View Visualizations button is weirdly close to the bottom of image. Adding some margin there would be good

![screen shot 2016-03-20 at 7 49 38 pm](https://cloud.githubusercontent.com/assets/6422954/13909694/fc762b7a-eed4-11e5-99aa-d7463faeabdb.png)

**Comment by chrismattmann** [comment]
any progress here?
