### ISSUE TITLE
Come up with standardized nav bar design

### ISSUE THREAD

**Issue by lorsposto** [USCDataScience/polar.usc.edu#46]
Right now there are slight nav bar inconsistencies between the main/D3 pages and Facetview/Banana pages, both in link content and details e.g. spacing.
- Come up with specs & mockup for color/font/size/spacing etc as standard to implement across all pages
- Come up with nav bar content plan that makes sense across all pages but is still concise. Mostly being able to incorporate clear links to Facetview and Banana without cluttering the nav bar too much (with what is already there)

**Comment by lorsposto** [comment]
also behavior, as the nav bar is persistent on the static pages but fixed on Facetview and banana

**Comment by chrismattmann** [comment]
is this progress helped by #55 ?

**Comment by luuj** [comment]
Here is a start on some nav-bar rules as well as D3 page rules I have thought of so far:
https://docs.google.com/document/d/1-Xu_96AB5Ot-nIXk2SsVHF9rVIxg7QeQs_zjgfxqzt8/edit

Feel free to add some rules @lorsposto @chrismattmann @janethkim @titusjung @ruthvik947

**Comment by chrismattmann** [comment]
requested permission for chris.mattmann@gmail.com

**Comment by luuj** [comment]
sent an invite, let me know if it doesn't work
