### ISSUE TITLE
Make D3 Visualizations Dynamic by Pulling from Solr content instead of local static files

### ISSUE THREAD

**Issue by janethkim** [USCDataScience/polar.usc.edu#50]

**Comment by chrismattmann** [comment]
any progress? @janethkim @lorsposto

**Comment by janethkim** [comment]
can look at branch dynamic_solr, I'm working on that right now. Successfully got the piechart to pull from the geo collection. Having a bit of trouble with updating the linechart so that it can pull from solr since in solr there isn't a date field for when the document was uploaded

**Comment by chrismattmann** [comment]
hrm, @lorsposto why isn't there a date?

**Comment by chrismattmann** [comment]
thanks for the update, @janethkim

**Comment by lorsposto** [comment]
@chrismattmann there is tstamp for the crawl date

**Comment by chrismattmann** [comment]
i think @janethkim is talking about extracted date. Is this one dependent on #51 ?

**Comment by titusjung** [comment]
see  #119
