### ISSUE TITLE
Extract temporal data from Solr documents

### ISSUE THREAD

**Issue by ruthvik947** [USCDataScience/polar.usc.edu#51]
Resources:
- https://github.com/manalishah/NLTKRest/tree/master/nltkrest
- http://www.nltk.org/api/nltk.html
- https://github.com/manalishah/nltk_contrib/blob/master/nltk_contrib/timex.py
- https://github.com/thammegowda/parser-indexer

**Comment by chrismattmann** [comment]
...any progress here @ruthvik947 @lorsposto

**Comment by ruthvik947** [comment]
hi @chrismattmann! i'm currently extracting the temporal data but i'm a little unclear on how to (i.e. the format and more) re-index that into the new core to make it useful.

**Comment by ruthvik947** [comment]
Todo:
- Update timex.py regexes to convert relative dates to python date strings/objects
- Make year extraction more realistic (all 4 digit numbers are being considered)

**Comment by chrismattmann** [comment]
please work with @lorsposto and look at http://github.com/manalishah/NLTKRest.git

**Comment by ruthvik947** [comment]
Refer to: https://github.com/lorsposto/solr-enrich/pull/5

**Comment by chrismattmann** [comment]
OK so is this done?
