### ISSUE TITLE
Fix team 24 header styles

### ISSUE THREAD

**Issue by lorsposto** [USCDataScience/polar.usc.edu#62]
Something wacky is going on with the styles for the team 24 header. Might be an artifact of the stylesheet they added.

![screen shot 2016-03-30 at 4 47 39 pm](https://cloud.githubusercontent.com/assets/6422954/14161266/20f6a05a-f697-11e5-8bc9-505370c1da6c.png)

**Comment by ruthvik947** [comment]
FYI @titusjung I think I modified the CSS of the main header so this could be my fault. Let me know if things you do don't fix it.

**Comment by chrismattmann** [comment]
hmmm what's the status on this here, thoughts? Can someone fix this?

**Comment by luuj** [comment]
Nav bar has been fixed. Do not know what is wrong with "Byte Frequency Analysis" or "File Header/Trailer Analysis" as their widgets are not loading for me.
