### ISSUE TITLE
Team16 failed to load enrichment bar chart data

### ISSUE THREAD

**Issue by chrismattmann** [USCDataScience/polar.usc.edu#98]
FYI: Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by AravindRam** [comment]
Hi @chrismattmann  

Fixed the issue and made a pull request #109 as well.

**Comment by chrismattmann** [comment]
thanks @AravindRam investigating!

**Comment by chrismattmann** [comment]
See my comment on #109 which I already merged. It's looking for http://polar.usc.edu/data/team16data/hw2json/barchartData.json which doesn't exist still can you update the page link?

**Comment by AravindRam** [comment]
@chrismattmann 

Professor,

I am able to get the JSON and the page is getting loaded now. So, I feel the issue is resolved. Please let me know if it is fixed or not.

Thanks

**Comment by chrismattmann** [comment]
👍 works fine great job @AravindRam
